### ISSUE TITLE
DaggerApplicationComponent.builder是什么

### ISSUE THREAD

**Issue by teemoY** [luxiaoming/dagger2Demo#1]
半天没找到DaggerApplicationComponent.builder().androidModule

**Comment by luxiaoming** [comment]
这个是Dagger2生成的代码，位置在\dagger2Demo\app\build\generated\source\apt\debug\com\xm\dagger2demo
编译一下app就出来了。

**Comment by teemoY** [comment]
回复好快呀，谢啦
