### ISSUE TITLE
官网最新2.24你的为啥是2.5

### ISSUE THREAD

**Issue by kscMaster** [luxiaoming/dagger2Demo#5]

**Comment by luxiaoming** [comment]
这个就是官网的。。

**Comment by kscMaster** [comment]
![Snipaste_2019-10-08_15-15-05](https://user-images.githubusercontent.com/19183142/66374825-71a28a80-e9de-11e9-9dc0-f18ac277710b.png)
好奇怪

**Comment by luxiaoming** [comment]
> ![Snipaste_2019-10-08_15-15-05](https://user-images.githubusercontent.com/19183142/66374825-71a28a80-e9de-11e9-9dc0-f18ac277710b.png)
> 好奇怪

https://jcenter.bintray.com/com/google/dagger/dagger/

**Comment by kscMaster** [comment]
好吧，github上的readme不更新了...

**Comment by kscMaster** [comment]
回复的很快，看来你闲得慌

**Comment by luxiaoming** [comment]
上头。。。
